# Generated by Django 4.2.4 on 2024-07-18 09:06

from django.db import migrations, models
import interview.models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_alter_interview_parsed_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_code',
            field=models.CharField(default=interview.models.generate_interview_code, max_length=255),
        ),
    ]
