# Generated by Django 4.2.4 on 2024-07-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_alter_interview_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
