# Generated by Django 4.2.4 on 2024-07-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_alter_interview_interview_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='stage',
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Rescheduled', 'Rescheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=255),
        ),
    ]
