# Generated by Django 4.2.4 on 2024-07-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture_url',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
