# Generated by Django 4.2.4 on 2024-07-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=50)),
                ('transcript', models.TextField()),
                ('description', models.TextField()),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
