# Generated by Django 4.2.4 on 2024-07-28 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('category_id', models.IntegerField()),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-addedAt'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=50)),
                ('transcript', models.TextField()),
                ('description', models.TextField()),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
                ('visual_data', models.JSONField(blank=True, null=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='conversation.topic')),
            ],
            options={
                'ordering': ['-addedAt'],
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='conversation.video'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('videoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='conversation.video')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('text', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('videoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='conversation.video')),
            ],
        ),
    ]
