# Generated by Django 4.2.4 on 2024-07-30 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='topic',
        ),
    ]
