# Generated by Django 4.2.4 on 2024-07-17 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-addedAt'],
            },
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-addedAt']},
        ),
        migrations.AddField(
            model_name='video',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='conversation.topic'),
        ),
    ]
