# Generated by Django 4.2.4 on 2024-07-24 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation', '0003_alter_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='visual_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('videoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='conversation.video')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('text', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('videoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='conversation.video')),
            ],
        ),
    ]
